---
title: "Parallel Computing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Parallel Computing Example

```{r cars}
# Bootstrap CI for Normal Distribution

lallcom <- function(parlis, M, Nsim){
  
  mlf <- function(y, parm){
    ml = suppressWarnings(sum(log(dnorm(x = y, mean = parm[1], sd = parm[2]))))
    return(-ml)
  }
  
  BootCI <- function(parm, n=1, parsd, inipar, M = 5000, alpha = 0.05, seed = NULL){
    npar = length(parm)
    Bfun <- function(parm, nn){
      while(TRUE){
        ystar = rnorm(n = nn, mean = parm[1], sd = parm[2])
        est = optim(inipar, mlf, y = ystar, hessian = TRUE)
        bsd = tryCatch(sqrt(diag(solve(est$hessian))), error = function(e) e)
        if (!is(bsd, 'error')){
          res = c(est$par, bsd)
          break
        }
      }
      return(res)
    }
    Bres = t(replicate(n = M, expr = Bfun(parm = parm, nn = n), simplify = TRUE))
    bqt1 = t(apply(Bres[,1:npar], 2, function(x) {quantile(x, probs = c(1-alpha/2, alpha/2))}))
    h1ci = 2*parm - bqt1
        return(t(h1ci))
  }
  
  cci <- function(nn, parm, M){
    truepar = parm
    while(TRUE){
      rn = rnorm(n = nn, mean = parm[1], sd = parm[2])
      est = optim(inipar, mlf, y = rn, hessian = TRUE)
      sdw = tryCatch(solve(est$hessian), error = function(e) e)
      if (!is(sdw, 'error')){
        sdw = sqrt(diag(sdw))
        break
      } 
    }
    bci = BootCI(parm = est$par, n = nn, parsd = sdw, M = M, inipar = inipar)
    ci = c(n, truepar, est$par, bci)
    return(ci)
  }
  
  parm = parlis[2:3]
  n = parlis[1]
  inipar = parm - 2
  ci = t(replicate(n = Nsim, expr = cci(nn = n, parm = parm, M = M), simplify = TRUE))
  return(ci)
}


#############################################################
#
# Parallal Computing 
#
#############################################################

library(parallel)

no_cores <- detectCores() - 1
cl <- makeCluster(no_cores)

mu = 5
n = c(100, 50, 25, 10)
sigma = c(8, 12, 15)
M=30
Nsim=25

clexp = list("lallcom", "Nsim", "M")
clusterExport(cl, clexp)

parlis = expand.grid(n = n, mu = mu, sigma = sigma)

# Compare time to run function using parApply and apply

system.time(a <-  parApply(cl = cl, parlis, 1, FUN = function(x) lallcom(parlis = x, M = M, Nsim = Nsim)))
stopCluster(cl)

system.time(b <-  apply(parlis, 1, FUN = function(x) lallcom(parlis = x, M = M, Nsim = Nsim)))


rm(list = ls())

```

# Parallel Computing time of Bubble Plot after frequency count of data

```{r}
dat_g <- function(n){
  x = rbinom(n,30,.5)
  x = as.data.frame(matrix(x, ncol = 2))
  return(x)
}

library(parallel)
require(ggplot2)
library(dplyr)
set.seed(123456)

bb_count <- function(x){
  x_f = as.data.frame(table(x$V1, x$V2))
  x_f = x_f[x_f$Freq != 0,]
  names(x_f) = c('V1', 'V2', 'Freq')
  x_f = as.data.frame(sapply(x_f, function(x) as.numeric(as.character(x))))
  x_f$Freq = x_f$Freq / sum(x_f$Freq)
  return(x_f)
}

b_plot <- function(x, n){
  p6 <- ggplot(x, aes(x = V1, y = V2, size = Freq)) +geom_point()+ggtitle(paste("n = ",n))
  print(p6)  
}

p_count <- function(x, a=NULL){
  x_f = as.data.frame(table(x$V1, x$V2))
  x_f = x_f[x_f$Freq != 0,]
  names(x_f) = c('V1', 'V2', 'Freq')
  x_f = as.data.frame(sapply(x_f, function(x) as.numeric(as.character(x))))
  return(x_f)
}

p_total <- function(x){
  x_f = x %>% group_by(V1, V2) %>%  summarise(Freq=sum(Freq))
  x_f$Freq = x_f$Freq / sum(x_f$Freq)
  return(x_f)
}

#####################################################################
options(scipen = 999)
time = NULL
nn = c(1000, 10000, 100000, 1000000, 10000000,20000000)
for (i in nn){
  n = i
  lo = ifelse(n/2 < 100000, 1, 40)
  ab = as.integer(seq(1,n/2, length.out = lo)[-c(1,lo)])
  par_tim = matrix(sort(c(1, ab, ab-1, n/2)), byrow = TRUE, ncol = 2)
  par_tim = matrix(par_tim[which(par_tim[,2]-par_tim[,1] > 2),], ncol = 2)
  par_tim[nrow(par_tim),2] = n/2
  
  # random number generation
  x = dat_g(n)
  
  # Frequency count and Bubble plot
  t1 = proc.time()
    x_f = bb_count(x)
    b_plot(x_f, n/2)
  t2 = proc.time()

  # Frequency count and Bubble plot using Parallel computing
  t3 = proc.time()
  
    # Detect number of CPU Cores on the current host
    no_cores <- detectCores() - 1
    
    
    cl <- makeCluster(no_cores)
    
    clexp = list('x', 'p_count')
    clusterExport(cl, clexp)
    
  
    t4 = proc.time()
      a <-  parApply(cl = cl, par_tim, 1, FUN = function(a) p_count(x = x[a[1]:a[2],]))
      stopCluster(cl)
      b = do.call(rbind, a)
      x_f1 = p_total(b)
      b_plot(x_f1, n/2)
    t5 = proc.time()

  print(c(n/2, (t2 - t1)[3], (t5 - t4)[3], (t5 - t3)[3]))
  time = as.data.frame(rbind(time, c(n = n/2, t_WOP = (t2 - t1)[3], t_P = (t5 - t4)[3], tt_p = (t5 - t3)[3])))
}




```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
library("reshape2")
library("ggplot2")

time <- melt(time, id = 'n')

library(ggplot2)
ggplot(time, aes(x=n, y=value, color = variable)) +
  geom_line(aes())+
  geom_point(aes())+xlab('n') + ylab('Time')+scale_color_manual(labels = c("Time without Parallel", "Parallel Time", 'Total Parallel Time'), values = c('Red', 'Black', 'Blue'))
```

# Using doParallel, fitting GLM model on bootstrap sample using parallel and without parallel

```{r}
library(doParallel)
cl <- makeCluster(detectCores())
registerDoParallel(cl)
# machine learning code goes in here



x <- iris[which(iris[,5] != "setosa"), c(1,5)]
trials <- 1000

ptime <- system.time({
  r <- foreach(icount(trials), .combine=cbind) %dopar% {
    ind <- sample(100, 100, replace=TRUE)
    result1 <- glm(x[ind,2]~x[ind,1], family=binomial(logit))
    coefficients(result1)
  }
})[3]
ptime


stime <- system.time({
  r <- foreach(icount(trials), .combine=cbind) %do% {
    ind <- sample(100, 100, replace=TRUE)
    result1 <- glm(x[ind,2]~x[ind,1], family=binomial(logit))
    coefficients(result1)
  }
})[3]
stime
stopCluster(cl)


```

# Example of doRedis, for calculating pi using MPI technique

```{r}
library("doRedis")
registerDoRedis("jobs")
startLocalWorkers(n=2, queue="jobs") 
options('redis:num'=TRUE)
system.time(foreach(icount(200),.combine=sum, 
        .multicombine=TRUE ,.inorder=FALSE) %dopar%
  4*sum((runif(1000000)^2 + runif(1000000)^2) <1)/200000000)
removeQueue("jobs")


require('doRedis')
redisWorker('jobs')
```
